/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccinationprograme;
import java.util.Iterator;

/**
 *
 * @author josh
 */
public class VaccineGUI extends javax.swing.JFrame {

    /**
     * Creates new form VaccineInterface */
    private VaccineInterface vaccQueue;
    public VaccineGUI() {
        vaccQueue = new VaccinePriority();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TitlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BodyPanel = new javax.swing.JPanel();
        PatientNameLabel = new javax.swing.JLabel();
        PatientConditionLabel = new javax.swing.JLabel();
        PatientAgeLabel = new javax.swing.JLabel();
        PatientNameField = new javax.swing.JTextField();
        PatientAgeField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListTextArea = new javax.swing.JTextArea();
        AddVaccineList = new javax.swing.JButton();
        DisplayAllList = new javax.swing.JButton();
        DisplayNumberQueue = new javax.swing.JButton();
        ApproveVaccineSchedule = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitlePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 0));
        jLabel1.setText("Covid-19 Vaccination Programme");

        javax.swing.GroupLayout TitlePanelLayout = new javax.swing.GroupLayout(TitlePanel);
        TitlePanel.setLayout(TitlePanelLayout);
        TitlePanelLayout.setHorizontalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(117, 117, 117))
        );
        TitlePanelLayout.setVerticalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        BodyPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PatientNameLabel.setText("Please enter your name");

        PatientConditionLabel.setText("Do you have any medical conditions? Yes or No");

        PatientAgeLabel.setText("Please enter your age");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ListTextArea.setEditable(false);
        ListTextArea.setColumns(20);
        ListTextArea.setRows(5);
        jScrollPane1.setViewportView(ListTextArea);

        AddVaccineList.setText("Add to vaccination list");
        AddVaccineList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVaccineListActionPerformed(evt);
            }
        });

        DisplayAllList.setText("Display vaccination list");
        DisplayAllList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayAllListActionPerformed(evt);
            }
        });

        DisplayNumberQueue.setText("Dipsplay vaccination queue numbers");
        DisplayNumberQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayNumberQueueActionPerformed(evt);
            }
        });

        ApproveVaccineSchedule.setBackground(new java.awt.Color(51, 204, 0));
        ApproveVaccineSchedule.setForeground(new java.awt.Color(0, 0, 0));
        ApproveVaccineSchedule.setText("Approve next schedule of vaccinations");
        ApproveVaccineSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApproveVaccineScheduleActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Yes");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("No");

        javax.swing.GroupLayout BodyPanelLayout = new javax.swing.GroupLayout(BodyPanel);
        BodyPanel.setLayout(BodyPanelLayout);
        BodyPanelLayout.setHorizontalGroup(
            BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(BodyPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DisplayNumberQueue)
                    .addComponent(DisplayAllList)
                    .addComponent(AddVaccineList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(ApproveVaccineSchedule)
                .addGap(38, 38, 38))
            .addGroup(BodyPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PatientAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BodyPanelLayout.createSequentialGroup()
                        .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PatientNameLabel)
                            .addComponent(PatientAgeLabel)
                            .addComponent(PatientConditionLabel))
                        .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BodyPanelLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(PatientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BodyPanelLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jRadioButton1)
                                .addGap(31, 31, 31)
                                .addComponent(jRadioButton2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BodyPanelLayout.setVerticalGroup(
            BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyPanelLayout.createSequentialGroup()
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BodyPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(PatientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyPanelLayout.createSequentialGroup()
                        .addContainerGap(36, Short.MAX_VALUE)
                        .addComponent(PatientNameLabel)))
                .addGap(30, 30, 30)
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientAgeLabel)
                    .addComponent(PatientAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientConditionLabel)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BodyPanelLayout.createSequentialGroup()
                        .addComponent(AddVaccineList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DisplayAllList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DisplayNumberQueue))
                    .addComponent(ApproveVaccineSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayNumberQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayNumberQueueActionPerformed
        // TODO add your handling code here:
        ListTextArea.append("There are " + vaccQueue.size() + " people waiting for the vaccine."+ "\n");
    }//GEN-LAST:event_DisplayNumberQueueActionPerformed

    private void AddVaccineListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVaccineListActionPerformed
        // Check if any of the fields are empty
    if (PatientNameField.getText().isEmpty() || PatientAgeField.getText().isEmpty()) {
        ListTextArea.append("\nValues cannot be empty, please enter all information before attempting to save details.\n");
    } else {
        String name, condition;
        int age = Integer.parseInt(PatientAgeField.getText());
        Recipient r = new Recipient();
        int priorityINT;

        name = PatientNameField.getText();
        condition = jRadioButton1.isSelected() ? "Yes" : "No";
        r.setName(name);
        r.setCondition(condition);
        r.setAge(age);

        if (jRadioButton1.isSelected()) {
            priorityINT = 6;
        } else {
            switch (age) {
                case 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17:
                    priorityINT = 1;
                    break;

                case 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29:
                    priorityINT = 2;
                    break;
                    
                   case 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44:
                    priorityINT = 3;
                    break; 
                    
                    case 45, 46, 47, 48, 49, 50, 51, 52, 53, 54:
                    priorityINT = 4;
                    break;
                    
                    case 55, 56, 57, 58, 59, 60, 61, 62, 63, 64:
                    priorityINT = 5;
                    break;
                    
                    case 65, 66, 67, 68, 69:
                    priorityINT = 6;
                    break;
                    
                    case 70, 71, 72, 73, 74:
                    priorityINT = 7;
                    break;

                    case 75, 76, 77, 78, 79:
                    priorityINT = 8;
                    break;
                    
                   case 80, 81, 82, 83, 84, 85, 86, 87, 88, 89:
                   priorityINT = 9;
                   break;

                case 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100:
                    priorityINT = 10;
                    break;

                default:
                    ListTextArea.append("\nInvalid age.\n");
                    return;
            }
        }

        int priority = priorityINT;
        vaccQueue.enqueue(priority, r);

        ListTextArea.append(name + " Recipient details have been added to the vaccine queue\n");
        PatientNameField.setText("");
        PatientAgeField.setText("");
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
    }
    }//GEN-LAST:event_AddVaccineListActionPerformed

    private void DisplayAllListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayAllListActionPerformed
       ListTextArea.append("Recipients waiting in the queue: ");

    int position = 1;

    Iterator<VaccineElement> iterator = vaccQueue.iterator();
    while (iterator.hasNext()) {
        VaccineElement ve = iterator.next();
        Recipient r = (Recipient) ve.getElement();

        ListTextArea.append(String.format(
            "Position: %d, Name: %s, Age: %d, Condition: %s, Priority: %d\n",
            position, r.getName(), r.getAge(), r.getCondition(), ve.getKey()
        ));

        position++;
    }
    }//GEN-LAST:event_DisplayAllListActionPerformed

    private void ApproveVaccineScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveVaccineScheduleActionPerformed
        if(!vaccQueue.isEmpty()){
            VaccineElement pqelem = (VaccineElement)vaccQueue.dequeue();
            Recipient r1 = (Recipient)pqelem.getElement();
            
            ListTextArea.append("Vaccine Schedule Group"+pqelem.getKey()+" is ready for vaccination");
           
        }
        else
            ListTextArea.append("There are no more patients waiting"+ "\n");
      
    }//GEN-LAST:event_ApproveVaccineScheduleActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VaccineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VaccineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VaccineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VaccineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VaccineGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddVaccineList;
    private javax.swing.JButton ApproveVaccineSchedule;
    private javax.swing.JPanel BodyPanel;
    private javax.swing.JButton DisplayAllList;
    private javax.swing.JButton DisplayNumberQueue;
    private javax.swing.JTextArea ListTextArea;
    private javax.swing.JTextField PatientAgeField;
    private javax.swing.JLabel PatientAgeLabel;
    private javax.swing.JLabel PatientConditionLabel;
    private javax.swing.JTextField PatientNameField;
    private javax.swing.JLabel PatientNameLabel;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
