/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccinationprograme;

/**
 *
 * @author josh
 */
public class VaccineGUI extends javax.swing.JFrame {

    /**
     * Creates new form VaccineInterface */
    private VaccineInterface vaccQueue;
    public VaccineGUI() {
        vaccQueue = new VaccinePriority();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BodyPanel = new javax.swing.JPanel();
        PatientNameLabel = new javax.swing.JLabel();
        PatientConditionLabel = new javax.swing.JLabel();
        PatientAgeLabel = new javax.swing.JLabel();
        PatientNameField = new javax.swing.JTextField();
        PatientAgeField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListTextArea = new javax.swing.JTextArea();
        AddVaccineList = new javax.swing.JButton();
        DisplayAllList = new javax.swing.JButton();
        DisplayNumberQueue = new javax.swing.JButton();
        ApproveVaccineSchedule = new javax.swing.JButton();
        PatientConditionField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitlePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 0));
        jLabel1.setText("Covid-19 Vaccination Programme");

        javax.swing.GroupLayout TitlePanelLayout = new javax.swing.GroupLayout(TitlePanel);
        TitlePanel.setLayout(TitlePanelLayout);
        TitlePanelLayout.setHorizontalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(117, 117, 117))
        );
        TitlePanelLayout.setVerticalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        BodyPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PatientNameLabel.setText("Please enter your name");

        PatientConditionLabel.setText("Do you have any medical conditions? Yes or No");

        PatientAgeLabel.setText("Please enter your age");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ListTextArea.setEditable(false);
        ListTextArea.setColumns(20);
        ListTextArea.setRows(5);
        jScrollPane1.setViewportView(ListTextArea);

        AddVaccineList.setText("Add to vaccination list");
        AddVaccineList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVaccineListActionPerformed(evt);
            }
        });

        DisplayAllList.setText("Display vaccination list");
        DisplayAllList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayAllListActionPerformed(evt);
            }
        });

        DisplayNumberQueue.setText("Dipsplay vaccination queue numbers");
        DisplayNumberQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayNumberQueueActionPerformed(evt);
            }
        });

        ApproveVaccineSchedule.setBackground(new java.awt.Color(51, 204, 0));
        ApproveVaccineSchedule.setForeground(new java.awt.Color(0, 0, 0));
        ApproveVaccineSchedule.setText("Approve next schedule of vaccinations");
        ApproveVaccineSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApproveVaccineScheduleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BodyPanelLayout = new javax.swing.GroupLayout(BodyPanel);
        BodyPanel.setLayout(BodyPanelLayout);
        BodyPanelLayout.setHorizontalGroup(
            BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(BodyPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PatientNameLabel)
                    .addComponent(PatientAgeLabel)
                    .addComponent(PatientConditionLabel))
                .addGap(56, 56, 56)
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PatientNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(PatientAgeField)
                    .addComponent(PatientConditionField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BodyPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DisplayNumberQueue)
                    .addComponent(DisplayAllList)
                    .addComponent(AddVaccineList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(ApproveVaccineSchedule)
                .addGap(38, 38, 38))
        );
        BodyPanelLayout.setVerticalGroup(
            BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyPanelLayout.createSequentialGroup()
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BodyPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(PatientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PatientNameLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientAgeLabel)
                    .addComponent(PatientAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientConditionLabel)
                    .addComponent(PatientConditionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BodyPanelLayout.createSequentialGroup()
                        .addComponent(AddVaccineList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DisplayAllList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DisplayNumberQueue))
                    .addComponent(ApproveVaccineSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayNumberQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayNumberQueueActionPerformed
        // TODO add your handling code here:
        ListTextArea.append("There are " + vaccQueue.size() + " people waiting for the vaccine."+ "\n");
    }//GEN-LAST:event_DisplayNumberQueueActionPerformed

    private void AddVaccineListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVaccineListActionPerformed
        // TODO add your handling code here:
        
        if(PatientNameField.getText().isEmpty() & PatientAgeField.getText().isEmpty() && PatientNameField.getText().isEmpty()){
            ListTextArea.append("\n"+"Values cannot be empty, please enter all information before attempting to save details."+"\n");
        }
                
                
        else
                {
           
         String name, condition;
        int age = Integer.parseInt(PatientAgeField.getText());
        int priority;
        Recipient r = new Recipient();
        //This was used in MaterHospital to input the priority manually, since thie priority is decided by Age + Condition, this is useless.
        Integer priorityINT;
        //Integer ageINT;
        
         
            if(age <= 17) {
                priorityINT = 1;
                priority = priorityINT.intValue();
                vaccQueue.enqueue(priority,r);
                name = PatientNameField.getText();
                age = Integer.parseInt(PatientAgeField.getText());
                condition = PatientConditionField.getText();
                r.setName(name);
                r.setCondition(condition);
                r.setAge(age);
                
            }
            else if(age >= 18 && age <=29 &&PatientConditionField.getText().equalsIgnoreCase("No") ) {
                priorityINT = 2;
                priority = priorityINT.intValue();
                vaccQueue.enqueue(priority,r);
                name = PatientNameField.getText();
                age = Integer.parseInt(PatientAgeField.getText());
                condition = PatientConditionField.getText();
                r.setName(name);
                r.setCondition(condition);
                r.setAge(age);
                
            }
            
            else if(age >= 30 && age <=44 &&PatientConditionField.getText().equalsIgnoreCase("No") ) {
                priorityINT = 3;
                priority = priorityINT.intValue();
                vaccQueue.enqueue(priority,r);
                name = PatientNameField.getText();
                age = Integer.parseInt(PatientAgeField.getText());
                condition = PatientConditionField.getText();
                r.setName(name);
                r.setCondition(condition);
                r.setAge(age);
                
            }
            
            else if(age >= 45 && age <=54 &&PatientConditionField.getText().equalsIgnoreCase("No") ) {
                priorityINT = 4;
                priority = priorityINT.intValue();
                vaccQueue.enqueue(priority,r);
                name = PatientNameField.getText();
                age = Integer.parseInt(PatientAgeField.getText());
                condition = PatientConditionField.getText();
                r.setName(name);
                r.setCondition(condition);
                r.setAge(age);
                
            }
            
            
                
            
            
            else if(age >= 55 && age <=64 &&PatientConditionField.getText().equalsIgnoreCase("No") ) {
                priorityINT = 5;
                priority = priorityINT.intValue();
                vaccQueue.enqueue(priority,r);
                name = PatientNameField.getText();
                age = Integer.parseInt(PatientAgeField.getText());
                condition = PatientConditionField.getText();
                r.setName(name);
                r.setCondition(condition);
                r.setAge(age);
                
            }
            
            else if(age >= 18 && age <=64 &&PatientConditionField.getText().equalsIgnoreCase("Yes") ){
                priorityINT = 6;
                priority = priorityINT.intValue();
                vaccQueue.enqueue(priority,r);
                name = PatientNameField.getText();
                age = Integer.parseInt(PatientAgeField.getText());
                condition = PatientConditionField.getText();
                r.setName(name);
                r.setCondition(condition);
                r.setAge(age);
                
            }
            
         
            else if(age >= 65 && age <=69 &&PatientConditionField.getText().equalsIgnoreCase("No") ) {
                priorityINT = 7;
                priority = priorityINT.intValue();
                vaccQueue.enqueue(priority,r);
                name = PatientNameField.getText();
                age = Integer.parseInt(PatientAgeField.getText());
                condition = PatientConditionField.getText();
                r.setName(name);
                r.setCondition(condition);
                r.setAge(age);
                
            }
            
            else if(age >= 70 && age <=79 &&PatientConditionField.getText().equalsIgnoreCase("No") ) {
                priorityINT = 8;
                priority = priorityINT.intValue();
                vaccQueue.enqueue(priority,r);
                name = PatientNameField.getText();
                age = Integer.parseInt(PatientAgeField.getText());
                condition = PatientConditionField.getText();
                r.setName(name);
                r.setCondition(condition);
                r.setAge(age);
                
            }
            else if(age >= 80 && age <=89 &&PatientConditionField.getText().equalsIgnoreCase("No") ) {
                priorityINT = 9;
                priority = priorityINT.intValue();
                vaccQueue.enqueue(priority,r);
                name = PatientNameField.getText();
                age = Integer.parseInt(PatientAgeField.getText());
                condition = PatientConditionField.getText();
                r.setName(name);
                r.setCondition(condition);
                r.setAge(age);
                
            }
            
            else if(age >= 90 && age <=100 &&PatientConditionField.getText().equalsIgnoreCase("No") ) {
                priorityINT = 10;
                priority = priorityINT.intValue();
                vaccQueue.enqueue(priority,r);
                name = PatientNameField.getText();
                age = Integer.parseInt(PatientAgeField.getText());
                condition = PatientConditionField.getText();
                r.setName(name);
                r.setCondition(condition);
                r.setAge(age);
                
            }
            
             









        
        
        
        //name = PatientNameField.getText();
        //condition = PatientConditionField.getText();
        
        //age = new Integer (PatientAgeField.getText());
        //r.setName(name);
        //r.setCondition(condition);
        //r.setAge(age);
        //This doesn't actually seem to do anything, might be better to just try and work with the 
        //priority = r.getPriority();
        
     
        
        //How do I get this to display onto the text area for priority, and how do I sort it into groups.
        // Study material doesn't seem to work with this, and online resources are not working. I am legitmately stuck and out of ideas.
        //priorityINT = new Integer (PatientAgeField.getText());
        //WHERE DOES THIS GO.
        //I have no idea how to assign this getText.
        //priority = priorityINT.intValue();
        //accQueue.enqueue(priority,);

        
        //r.setAge(age);
        

        ListTextArea.append(PatientNameField.getText() + " Recipient details have been added to vaccine queue"+ "\n");
        PatientNameField.setText("");
        PatientAgeField.setText("");
        PatientConditionField.setText("");
                }
        
        
    }//GEN-LAST:event_AddVaccineListActionPerformed

    private void DisplayAllListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayAllListActionPerformed
        // TODO add your handling code here:
        ListTextArea.append("The recipients waiting in the queue...."+ "\n");
        ListTextArea.append(vaccQueue.printvaccueue()+ "\n");
    }//GEN-LAST:event_DisplayAllListActionPerformed

    private void ApproveVaccineScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveVaccineScheduleActionPerformed
        if(!vaccQueue.isEmpty()){
            VaccineElement pqelem = (VaccineElement)vaccQueue.dequeue();
            Recipient r1 = (Recipient)pqelem.getElement();
            
            ListTextArea.append("Vaccine Schedule Group"+pqelem.getKey()+" is ready for vaccination");
           
        }
        else
            ListTextArea.append("There are no more patients waiting"+ "\n");
      
    }//GEN-LAST:event_ApproveVaccineScheduleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VaccineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VaccineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VaccineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VaccineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VaccineGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddVaccineList;
    private javax.swing.JButton ApproveVaccineSchedule;
    private javax.swing.JPanel BodyPanel;
    private javax.swing.JButton DisplayAllList;
    private javax.swing.JButton DisplayNumberQueue;
    private javax.swing.JTextArea ListTextArea;
    private javax.swing.JTextField PatientAgeField;
    private javax.swing.JLabel PatientAgeLabel;
    private javax.swing.JTextField PatientConditionField;
    private javax.swing.JLabel PatientConditionLabel;
    private javax.swing.JTextField PatientNameField;
    private javax.swing.JLabel PatientNameLabel;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
